### ISSUE TITLE
read(buf, off, len) returning 0 bytes compared to FilterInputStream

### ISSUE THREAD

**Issue by ajohnson1** [nayuki/DEFLATE-library-Java#1]
Thank you for providing DEFLATE-library-java - it is good code and looks to be useful for me.

I notice [InflaterInputStream.java#L191](https://github.com/nayuki/DEFLATE-library-Java/blob/4775f5683e369f6d471de1dbc7a6f3c3b520c0c5/src/io/nayuki/deflate/InflaterInputStream.java#L191)

says:

> Note that 0 can be returned even if the end of stream hasn't been reached yet.

whereas [FilterInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/FilterInputStream.html#read-byte:A-int-int-) says if `len > 0` it blocks until data is available,
[JDK InflaterInputStream](https://docs.oracle.com/javase/8/docs/api/java/util/zip/InflaterInputStream.html#read-byte:A-int-int-) says than if `len > 0` it will block until some data can be decompressed and [InputStream](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#read-byte:A-int-int-) says if `len > 0` there is an attempt to read at least one byte.

Is there a reason for the change in the contract for `read(buf, off, len)` ? The code does actually sometimes return 0, perhaps at the end of a block, as shown by setting a breakpoint in [read()](https://github.com/nayuki/DEFLATE-library-Java/blob/4775f5683e369f6d471de1dbc7a6f3c3b520c0c5/src/io/nayuki/deflate/InflaterInputStream.java#L178) and running the unit tests. It means the code is not a drop-in replacement for other InputStreams or the JDK InflaterInputStream.

**Comment by nayuki** [comment]
Hi, thank you for raising this issue and providing relevant details. I apologize for the long delay in discovering this topic.

I believe you are right. I haven't given this codebase some love for many months, so it'll take a bit of time for me to remember the existing logic and figure out how to design an appropriate fix.

**Comment by nayuki** [comment]
So, I finally returned to focusing on my DEFLATE library developments (especially [Simple DEFLATE decompressor](https://github.com/nayuki/Simple-DEFLATE-decompressor) in C++).

I started reading over my [InflaterInputStream](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java) code, focusing on the read-array-returning-zero problem you highlighted. The context you provided was very helpful - such as the behavior of JDK classes, the breakpoint in the scalar [`read()`](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L156-L185) function, and the notion of a drop-in replacement.

I will walk through the logic of [`read(byte[] b, int off, int len)`](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L198) and figure out which cases lead to a 0 result.

0. [Lines 201~202](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L201-L202): If the interval [off, off + len) is not a (non-strict) subset of [0, b.length), throw an exception. Note that `read(new byte[0], 0, 0)` is legal.

0. [Lines 208~210](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L208-L210): If the requested read length is 0, without performing any underlying I/O or even stream decoding, check the current object state and return 0 if an EOF has been previous processed, otherwise return -1. Thereafter, the read length is positive.

0. [Lines 215~227](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L215-L227): If there are leftover bytes from the current LZ77 run (anywhere from 1 to 257 bytes remaining), copy them into the output. We're interested in the read return 0, so we'll assume there are no leftover bytes to copy.

0. [Lines 231~262](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L231-L262): While the state is 0 (the "neutral" state where the start of a DEFLATE block is expected; this happens initially, or immediately after reading an uncompressed block's length of 0x0000 and nlen of 0xFFFF, or immediately after the last byte of a non-empty uncompressed block, or immediately after the end of a Huffman-coded block), read another block header.

0. [Lines 264~278](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L264-L278): With the state being nonzero, either we read at least 1 byte from an uncompressed block (this cannot the be cause of the problem), or we head into [`readInsideHuffmanBlock()`](https://github.com/nayuki/DEFLATE-library-Java/blob/acb01805a28ca9fd6ce55a6e8f373805587f44fe/src/io/nayuki/deflate/InflaterInputStream.java#L287).

0. If the Huffman-coded block immediately ends (using symbol 256), the method will return 0, and the parent will also return 0.

As we can see, I wrote logic to repeatedly grab uncompressed blocks until a non-empty one is found, but I didn't apply the same logic to Huffman-coded blocks. Hence, it would be best to restructure the while-loop inside of `read(byte[],int,int)`.

**Comment by nayuki** [comment]
If I didn't make any mistakes, [this commit](https://github.com/nayuki/DEFLATE-library-Java/commit/36c3b71815c09efb3cb001290b948ea4a808693f) should solve your problem. [Subsequently](https://github.com/nayuki/DEFLATE-library-Java/commit/4dc65a890420552caaad4c0d21a892b0aa436ed6), for the scalar `read()`, I removed the while-loop and made an error out of the previous behavior of the array-read method.

**Comment by ajohnson1** [comment]
Thank you for those changes. As you can see from https://git.eclipse.org/c/mat/org.eclipse.mat.git/tree/plugins/org.eclipse.mat.hprof/src/io/nayuki/deflate/InflaterInputStream.java my code has diverged a bit from yours, so I'll have to see which changes I could apply. I had worked around the read returning 0 at the caller.

My changes are as follows:

1. Allow a clone of an InflaterInputStream.  This is to help have random access to a zip file. So before doing a read I could save the position of the underlying input stream, clone the InflatorInputStream, then do the read. To go back to the original position I would then move position of the underlying input stream to the previous position and read from the clone.
2. I've implemented a solution to issue #2 by allowing reads after a `detach()` to read any left over data in the input buffer, then to read data passed through from the underlying stream. That allows a caller of InflaterInputStream to see the EOF at the end of a GZIP member, then to detach, read the trailer, then if there is another header, read that, then call `attach()` to start reading compressed data.
3. I removed the `outputBuffer` as the data is also in the dictionary. This meant I had less data to clone.
4. Implemented `mark()`, `reset()` and `available()`. The dictionary can be used as a buffer of previous data. This wasn't completely general - it couldn't mark more than `DICTIONARY_LENGTH - OUTPUT_BUFFER_LENGTH` and didn't work when detached, but was useful enough for me.

If any of those sound useful I could prepare a pull request.

**Comment by nayuki** [comment]
Thanks for the quick reply and also taking care of patching / working around the code by yourself years ago. Don't worry about the divergence, and definitely don't feel compelled to adopt the patches. I'm not even fully confident in the code myself, and I'm doing some major refactoring now, and have plans for a much more comprehensive test suite to exercise more branches and the state space.

You're welcome to keep your current approach, but I hestitate to adopt it in the library. My worry about your `attach()` concept is that it's like duplicating the constructor functionality, and makes an object even more stateful and have a more complicated lifecycle. I feel that "create, use, discard" is a worthy ideal to aim for.

Good observation about outputBuffer. I'll make that simplification on my end too. Using the dictionary for mark/reset is clever, but I worry about applications that might need arbitrary large marks (as opposed to the fixed 32768-byte dictionary of DEFLATE). No need for a pull request, I'm making some major changes already.

**Comment by ajohnson1** [comment]
I think there is minor bug with `mark()/reset()/markSupported()`. As these are not overridden they go to `FilterInputStream` which then delegates to the wrapped stream. If the wrapped stream returns true for `markSupported()` then a `mark()/reset()` is going to replay some of the compressed data which won't work for the Inflater. If it returs false, but `reset()` goes to a defined position, then that also won't work for the Inflater. The simple solution is to return false for `markSupported()`, do nothing for `mark()` and throw an IOException for `reset()`.

To properly support `mark()/reset()` for all buffer sizes could be done by using the dictionary as a mark buffer, and resizing the dictionary as necessary (and allow any size of dictionary >=32K, not just a power of 2), or with a separate mark buffer for the oldest data.

**Comment by nayuki** [comment]
You're right, I forgot to take `FilterInputStream`'s undesirable mark behavior into account. My `InflaterInputStream` [no longer has `FilterInputStream` as a superclass](https://github.com/nayuki/DEFLATE-library-Java/commit/08f147103af5ba8f42a638cb19d5ef91fca6a1bd).

Currently the dictionary size must be a power of 2 because it uses AND-masking to do wraparound for the index; this should be faster than modulo (or compare-and-branch?). Having another mark buffer for old data would complicate things more...

**Comment by nayuki** [comment]
Closing now because the bug has been fixed, and the inflater internal and external architecture is undergoing major changes which means your comments are no longer applicable.

You are welcome to open new issues pertaining to the current version of the codebase.
